const configRoutes = {
  home: "/",
  login: "/login",
  register: "/register",
  registerInfo: "/register/info",
  hireTeam: "/hireTeam",
  hiretemaSize: "/hireTeam/quiz/size-company",
  hireteamWorkLength: "/hireTeam/quiz/work-length",
  hireteamWorkWeek: "/hireTeam/quiz/work-week",
  hireteamWorkSkill: "/hireTeam/quiz/work-skill",
  hireteamWorkStart: "/hireTeam/quiz/work-start",
  hireteamWorkForm: "/hireTeam/quiz/work-form",
  hireteamWorkWage: "/hireTeam/quiz/work-wage",
  hireteamCustomInfo: "/hireTeam/quiz/info",
  freelancers: "/freelancers",
  infoFreelancers: "/freelancers/info/:id",
  homeAdmin: "/admin/home",
  adminListEmployees: "/admin/list-employees",
  adminCreateEmployees: "/admin/create-employees",
  adminCreateTeam: "/admin/create-team",
  adminListTeam: "/admin/list-team",
  adminUpdateEmployees: "/admin/update-employees",
  adminUpdateTeam: "/admin/update-team",
  adminHistoryOrder: "/history-order",
  profileCustomer: "/profile",
  adminListOrder: "/admin/list-order",
  contract: "/contract",
  statement: "contract/:id",
};

export default configRoutes;
